---
title: "Trash related service requests and ECB citations"
output: html_document
params:
  area_name: ["Ellwood Park/Monument"]  #, "Baltimore Highlands"
  area_type: "neighborhood"
  year_start: 2016
  # If union is TRUE, the union_name is required
  union: FALSE # TRUE
  union_name: NULL
  # Map parameters
  asp: "9:6.25" # "17:11"  # "3:2"  # "16:9"
  diag_ratio: 0.08
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(sf)
library(mapbaltimore)
library(ggplot2)
library(dplyr)
library(stringr)
library(lubridate)

# Set default theme
theme_set(theme_minimal())
```

## Get area

```{r get_area}
# Get an sf object with all neighborhoods unioned into a single area
area <- get_area(params$area_type,
                 params$area_name,
                 union = params$union)

if (params$union) {
  area$name <- params$union_name

# Get an sf object with no union
  area_not_union <-
  get_area(
    params$area_type,
    params$area_name,
    union = FALSE)
}

area_layer <- geom_sf(data = area, fill = NA, color = "black", linetype = "dashed")

```

## Get selected requests

```{r get_requests}

# Define list of trash-related request types
select_request_types <-
  c("HCD-Sanitation Property",
    "HCD-Illegal Dumping",
    "SW-Dirty Street",
    "SW-Dirty Alley",
    "SW-Municipal Trash Can Concern",
    "SW-Municipal Trash Can Stolen/Lost")

# Get 2021 requests of each type
requests <-
  purrr::map_dfr(
    select_request_types,
    ~ get_area_requests(
      area = area,
      year = 2021,
      request_type = .x)
    )
```

```{r map_requests}
requests %>% 
  ggplot() +
  geom_sf(aes(color = sr_type)) +
  geom_sf(data = area, fill = NA, color = "black", linetype = "dashed") +
  theme_void()

requests %>% 
  ggplot() +
  geom_sf(aes(color = days_to_close), alpha = 0.6) +
  area_layer +
  scale_color_viridis_c() +
  theme_void()
```

```{r plot_requests}
requests %>% 
  ggplot(aes(x = days_to_close, y = sr_type, color = sr_type), alpha = 0.6) +
  geom_point() +
  theme_minimal()
```

```{r request_table}
requests %>%
  st_drop_geometry() %>% 
  count(sr_type, name = "requests", sort = TRUE) %>% 
  gt::gt()
```

## Get selected citations

```{r get_citations}
if (params$area_type %in% c("neighborhood", "council district", "police district")) {
  citations <-
    get_area_citations(
      area_type = params$area_type,
      area_name = params$area_name,
      description = "TRASH"
    ) %>%
    filter(
      year(violation_date) >= params$year_start
    ) %>%
    # Pull street number (address), block number, and street name from location
    mutate(
      street_number = readr::parse_number(violation_location),
      block_number = floor(street_number / 100) * 100,
      street_name = str_trim(str_remove(violation_location, glue::glue("^{street_number}|^0{street_number}")))
    )
}

citations_source <- "Source: Environmental Control Board (ECB) Citations/Open Baltimore"

```

# Where is trash an issue in the area?

- Citations by block
- Citations by block number and street name

```{r map_citations}
citations %>% 
  ggplot() +
  geom_sf(aes(color = description)) +
  area_layer +
  theme_void() +
  labs(caption = citations_source)
```

## Citations by block

```{r citation_block}
citations %>% 
  ggplot() +
    geom_bar(aes(x = as.factor(block))) +
    coord_flip() +
    theme(axis.text.y = element_text(size = 5))

library(WVPlots)
citations %>%
  ClevelandDotPlot("block", sort = 1, title = "Citations per block") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 5))
```

```{r citation_type}
citations %>%
  ggplot() +
  geom_bar(aes(x = as.factor(block), fill = description)) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 5))
```

```{r citations_by_block_table}
citations %>%
  st_drop_geometry() %>%
  count(block, name = "citations", sort = TRUE) %>%
  gt::gt()
  
```


# Plot citations by block number and street

```{r plot_block_number_street}
# FIXME: Figure out a reproducible way for distinguishing between groups of streets
ns_street_cutoff <- 500 # Block number equal or less than this are in the NS group
ew_street_cutoff <- 500 # Block numbers greater than this are in the EW group

block_street_count <- citations |>
  sf::st_drop_geometry() |>
  count(street_name, block_number, name = "count", sort = TRUE) |>
  relocate(block_number, .before = street_name)

plot_block_street <- function(df, highlight_n = 10) {
  df |>
  ggplot() +
  geom_point(aes(x = count, y = block_number), size = 3, alpha = 0.85, color = "purple") +
  facet_wrap(~ street_name) +
  gghighlight::gghighlight(count > highlight_n)
}

ns_streets <-
  block_street_count |>
  filter(block_number <= ns_street_cutoff) |> # Limit plot to N-S streets
  plot_block_street()

ew_streets <-
  block_street_count |>
  filter(block_number > ew_street_cutoff) |> # Limit plot to E-W streets
  plot_block_street()

ns_streets + ew_streets
```


```{r table_block_number_street}
table_min_count <- 15

block_street_count |>
  filter(count >= table_min_count) |>
  gt::gt() |>
  gt::tab_header(
    title = glue::glue("Blocks in  {params$area_name} with {table_min_count} or more citations since {params$year_start}")
  ) |>
  gt::tab_source_note(
    citations_source
  )
```

# How are citations addressing the issue of trash in this area?

- Citation status
- Citations over time

## Citation status 

```{r citations_status}
citations %>%
  ggplot() +
  geom_bar(aes(x = citation_status, fill = description))
```

```{r citation_status_table}
citations %>%
  st_drop_geometry() %>%
  mutate(
    citation_status = case_when(
      citation_status == "A" ~ "Appealed",
      citation_status == "O" ~ "Open",
      citation_status == "P" ~ "Paid",
      citation_status == "V" ~ "Voided" # TODO: Should voided citations be excluded?
    )
  ) %>% 
  count(citation_status, name = "citations") %>%
  gt::gt()
```

```{r citation_status_by_block}
citations %>%
  ggplot() +
  geom_bar(aes(x = as.factor(block), fill = citation_status)) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 5))
```

## Citations over time

```{r total_citations_over_time}
#review this graph (binwidth)
citations %>%
  ggplot() +
  geom_freqpoly(aes(x = violation_date)) +
  labs(caption = citations_source)
```

```{r citation_status_over_time}
# review this graph - Different way to plot this out? Maybe 4 line graphs?
citations %>% 
  ggplot() +
  geom_freqpoly(aes(x = violation_date, color = citation_status)) +
  labs(caption = citations_source)
```


