---
title: "Trash related service requests and ECB citations"
output: rmdformats::downcute
params:
  area_name: ["Ellwood Park/Monument"]  #, "Baltimore Highlands"
  area_type: "neighborhood"
  year_start: 2016
  # If union is TRUE, the union_name is required
  union: FALSE # TRUE
  union_name: NULL
  # Map parameters
  asp: "9:6.25" # "17:11"  # "3:2"  # "16:9"
  diag_ratio: 0.08
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = TRUE)

library(sf)
library(mapbaltimore)
library(ggplot2)
library(dplyr)
library(stringr)
library(lubridate)
library(patchwork)
library(gt)

# Set default theme
theme_set(theme_minimal())
```

```{r pull_scripts}
#Gets the area type, name, nearby areas, and area outline (or Union info if applicable).
source('get_area_script.R')

#Gets selected type of requests, 6-months prior, area request info, and nearby areas request info. 
source('get_requests_script.R')

#Gets citations based on area type, provides citation source, area citations info, and nearby areas citations info.
source('get_citations_script.R')


source('get_area_blocks_script.R')
```

```{r city_and_neighborhood_maps}
#Creates map of Baltimore City.
city_map <- ggplot() +
  geom_sf(data = baltimore_city, fill = "grey") +
  geom_sf(data = neighborhoods, fill = NA, color = "black") +
  geom_sf(data = area, fill = "red", color = "red") +
  geom_sf(data = baltimore_city, size = 1, color = "black", fill = NA) +
  ggtitle("Baltimore City") +
  theme_void()

#Creates map of neighborhood.

area_map <- ggplot() +
  layer_area_data(area = area, data = parks, fill = "forestgreen", alpha = 0.8) +
  layer_area_streets(area = area, color = "gray85") +
  #layer_area_streets(area = area, sha_class = "all") +
  geom_sf(data = area, color = "black", size = 1, fill = NA) +
  theme_void() +
  labs(
    title = params$area_name
  )

#displays maps
city_map + area_map

```

# Service Requests

The location and the type of 311 service requests within the `r area$name` neighborhood
over the past `r months_prior` months is shown on the map below. 

```{r service_requests}
#Creates map of service requests colored by request type
area_requests %>% 
  ggplot() +
  geom_sf(data = blocks, fill = NA, color = "black") +        #Blocks layer
  geom_sf(data = area, color = "black", size = 1.25, fill = NA) +  #Neighborhood outline layer
  geom_sf(aes(color = sr_type)) +
  theme_void() +
  labs(
    title = "Area requests by type",
    color = "Service Request Type"
  )

```

# ECB Citations

```{r citations}


```

# Trash Issues

```{r trash_issues}


```

# Nearby Areas

```{r compare_with_nearby_areas}


```

```{r lower_requests_and_citations}


```

